// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHFMXx3w3neb-OHoN4FCm_9n17gooEmA',
    appId: '1:629053638876:web:75fd7bb1e1886c4d3c0c19',
    messagingSenderId: '629053638876',
    projectId: 'healthy-bites1',
    authDomain: 'healthy-bites1.firebaseapp.com',
    storageBucket: 'healthy-bites1.appspot.com',
    measurementId: 'G-SRV46LMR2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAqWYGMYSuULgmrqxfw78ZjUc0QvU0PeE',
    appId: '1:629053638876:android:9c3618a230f864763c0c19',
    messagingSenderId: '629053638876',
    projectId: 'healthy-bites1',
    storageBucket: 'healthy-bites1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANp8qX_IPrE2AxTzSZZuEEpmLaSesR-S0',
    appId: '1:629053638876:ios:2d68969910ece9c93c0c19',
    messagingSenderId: '629053638876',
    projectId: 'healthy-bites1',
    storageBucket: 'healthy-bites1.appspot.com',
    iosBundleId: 'com.example.healthyBites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANp8qX_IPrE2AxTzSZZuEEpmLaSesR-S0',
    appId: '1:629053638876:ios:2d68969910ece9c93c0c19',
    messagingSenderId: '629053638876',
    projectId: 'healthy-bites1',
    storageBucket: 'healthy-bites1.appspot.com',
    iosBundleId: 'com.example.healthyBites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtHFMXx3w3neb-OHoN4FCm_9n17gooEmA',
    appId: '1:629053638876:web:7918aa3e5bb097be3c0c19',
    messagingSenderId: '629053638876',
    projectId: 'healthy-bites1',
    authDomain: 'healthy-bites1.firebaseapp.com',
    storageBucket: 'healthy-bites1.appspot.com',
    measurementId: 'G-X1CNP8JBPY',
  );
}
